# Generated by Django 5.0.14 on 2026-07-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(default=1, help_text='Meal plan week number for rotation (e.g. Week 1, Week 2)')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('recipe_link', models.URLField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('carbs_g', models.DecimalField(blank=True, decimal_places=1, help_text='Carbohydrates in grams', max_digits=5, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=1, help_text='Protein in grams', max_digits=5, null=True)),
                ('fat_g', models.DecimalField(blank=True, decimal_places=1, help_text='Fat in grams', max_digits=5, null=True)),
                ('ingredients', models.JSONField(blank=True, default=list, help_text='List of ingredients needed')),
                ('is_pcos_friendly', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['week_number', 'day_of_week', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Basics', 'PCOS Basics'), ('Nutrition', 'Nutrition & Diet'), ('Exercise', 'Exercise & Fitness'), ('Hormones', 'Hormones & Health'), ('Fertility', 'Fertility'), ('Stress', 'Stress Management'), ('News', 'Latest News')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(help_text='Short teaser description')),
                ('content', models.TextField(help_text='Full markdown or rich text content')),
                ('source_name', models.CharField(blank=True, help_text='For news articles, specify source name', max_length=100)),
                ('source_url', models.URLField(blank=True, help_text='For news articles, link to original source', null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Workout', 'Workout'), ('Yoga', 'Yoga'), ('Meditation', 'Meditation')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='e.g. 15 mins • Beginner', max_length=255)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes')),
                ('description', models.TextField()),
                ('steps', models.JSONField(blank=True, default=list, help_text='Sequential steps/instructions')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.AddConstraint(
            model_name='mealplan',
            constraint=models.UniqueConstraint(fields=('week_number', 'day_of_week', 'meal_type'), name='unique_meal_plan_slot'),
        ),
    ]
