# Generated by Django 5.0.14 on 2026-07-05 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of period')),
                ('end_date', models.DateField(blank=True, help_text='End date of period (leave blank if current/ongoing)', null=True)),
                ('flow_level', models.CharField(choices=[('Spotting', 'Spotting'), ('Light', 'Light'), ('Medium', 'Medium'), ('Heavy', 'Heavy')], default='Medium', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyHabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('water_intake_ml', models.IntegerField(default=0, help_text='Total water consumed in ml')),
                ('water_goal_ml', models.IntegerField(default=2000, help_text='Target water goal in ml')),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Hours of sleep', max_digits=4, null=True)),
                ('exercise_completed', models.BooleanField(default=False)),
                ('yoga_completed', models.BooleanField(default=False)),
                ('meditation_completed', models.BooleanField(default=False)),
                ('mood', models.IntegerField(blank=True, help_text='Mood rating from 1 (poor) to 5 (excellent)', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight logged in kg', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='General comments or observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symptom_name', models.CharField(choices=[('Cramps', 'Cramps'), ('Bloating', 'Bloating'), ('Acne', 'Acne'), ('Fatigue', 'Fatigue'), ('Headache', 'Headache'), ('Mood Swings', 'Mood Swings'), ('Insomnia', 'Insomnia'), ('Cravings', 'Cravings'), ('Backache', 'Backache'), ('Nausea', 'Nausea')], max_length=50)),
                ('severity', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], default='Mild', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Specific symptom comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'symptom_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyhabitlog',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_daily_log'),
        ),
    ]
